---
title: "Conveyor Belt Fault Detection System"
baseurl: "/e20-co326-Conveyor-Belt-Fault-Detection"
url: "https://cepdnaclk.github.io"

theme: suspended_ceiling

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
